##
## settings
##
GeneralSettings:
  format: RobotAssemblerYaml
  formatVersion: 1.0
  angleUnit: degree ## degree/radian
  lengthUnit: mm ## m, mm, (inch)
  massUnit: g ## g,kg
  ## inertia-tensor(unit) massUnit * lengthUnit^2
  ## translation: [x, y, z]
  ## rotation: [ax, ay, az, angle]

##ConnectingConstraintSettings:
##   connecting-type-list:
##   connecting-type-match-list:
##   connecting-configuration-list:
ConnectingConstraintSettings:
  connecting-type-list: [ PEG_P, PEG_H, AXL_P, AXL_F, AXL_H, STUD_P, STUD_H ]
  ## pair: [a, b] ## configuration represents transoform from a to b
  connecting-type-match-list:
    -
      pair: [PEG_P, PEG_H]
      allowed-configuration: [flip-z, fixed]
    -
      pair: [AXL_P, AXL_F]
      allowed-configuration: [fixed]
    -
      pair: [AXL_P, AXL_H]
      allowed-configuration: [flip-z, fixed]
    -
      pair: [STUD_P, STUD_H]
      allowed-configuration: [fixed, rot90+y, flip-y, rot90-y]
  ##
  connecting-configuration-list:
    -
      name: fixed
      description: 'fixed with same coords'
    -
      name: flip-z
      description: 'flip over / rotate 180[deg] around z-axis'
      rotation: [0, 0, 1, 180]
    -
      name: flip-y
      description: 'flip over / rotate 180[deg] around y-axis'
      rotation: [0, 1, 0, 180]
    -
      name: rot90+y
      description: 'flip over / rotate 180[deg] around y-axis'
      rotation: [0, 1, 0, 90]
    -
      name: rot90-y
      description: 'flip over / rotate 180[deg] around y-axis'
      rotation: [0, 1, 0, -90]

#
# python3 gen_assembler.py | cat config_base.yaml - > ldraw_assembler_config.yaml
#
